const GLOSSARY = [
  { term:"ACL",     def:"Access Control List — a set of rules that permit or deny network traffic or file access based on criteria such as IP address or user identity." },
  { term:"APIPA",   def:"Automatic Private IP Addressing — Windows automatically assigns a 169.254.x.x address when no DHCP server is reachable." },
  { term:"APT",     def:"Advanced Persistent Threat — a prolonged, targeted cyberattack in which an attacker gains access and remains undetected for an extended period." },
  { term:"ARP",     def:"Address Resolution Protocol — maps an IP address to a MAC address on a local network. Results are cached in the ARP table." },
  { term:"AUP",     def:"Acceptable Use Policy — a document defining how employees and users may use company IT resources." },
  { term:"BIOS",    def:"Basic Input/Output System — legacy firmware that initializes hardware during boot. Largely replaced by UEFI." },
  { term:"BSoD",    def:"Blue Screen of Death — a Windows critical error screen caused by hardware failure, driver issues, or OS corruption." },
  { term:"BYOD",    def:"Bring Your Own Device — policy allowing employees to use personal devices for work tasks." },
  { term:"CCMP",    def:"Counter Cipher Mode with Block Chaining Message Authentication Code Protocol — AES-based encryption used in WPA2." },
  { term:"CMOS",    def:"Complementary Metal-Oxide-Semiconductor — the low-power memory chip (backed by a coin cell battery) that stores BIOS/UEFI settings." },
  { term:"CPU",     def:"Central Processing Unit — the primary processor of a computer; executes program instructions." },
  { term:"DaaS",    def:"Desktop as a Service — a cloud-based VDI solution where desktops are hosted and managed by a third-party provider." },
  { term:"DHCP",    def:"Dynamic Host Configuration Protocol — automatically assigns IP addresses, subnet masks, gateways, and DNS servers to network clients. Uses DORA (Discover, Offer, Request, Acknowledge)." },
  { term:"DIMM",    def:"Dual Inline Memory Module — the full-size RAM form factor used in desktop computers." },
  { term:"DISM",    def:"Deployment Image Servicing and Management — Windows tool that repairs the component store when SFC alone cannot fix system files." },
  { term:"DMZ",     def:"Demilitarized Zone — a network segment between the internal network and the internet that hosts publicly accessible services (web, email, DNS)." },
  { term:"DNS",     def:"Domain Name System — translates human-readable hostnames (e.g., google.com) into IP addresses." },
  { term:"DORA",    def:"Discover, Offer, Request, Acknowledge — the four-step DHCP process by which a client obtains an IP address." },
  { term:"DLP",     def:"Data Loss Prevention — security tools and policies that detect and prevent unauthorized transfer of sensitive data." },
  { term:"ECC",     def:"Error-Correcting Code — a type of RAM (or storage) that detects and automatically corrects single-bit memory errors. Used in servers and workstations." },
  { term:"ESD",     def:"Electrostatic Discharge — the sudden flow of static electricity that can permanently damage electronic components. Prevented with ESD straps and mats." },
  { term:"exFAT",   def:"Extended File Allocation Table — a file system with no 4 GB file size limit; natively supported by Windows and macOS. Ideal for USB drives shared between platforms." },
  { term:"FAT32",   def:"File Allocation Table 32 — a legacy file system limited to 4 GB maximum file size. Compatible with nearly all OSes." },
  { term:"FQDN",    def:"Fully Qualified Domain Name — a complete domain name specifying its exact location in the DNS hierarchy (e.g., mail.example.com)." },
  { term:"GFS",     def:"Grandfather-Father-Son — a backup rotation strategy using daily (Son), weekly (Father), and monthly (Grandfather) backup sets." },
  { term:"GPT",     def:"GUID Partition Table — modern disk partitioning scheme supporting drives larger than 2 TB and up to 128 partitions. Required for UEFI booting." },
  { term:"GPU",     def:"Graphics Processing Unit — handles rendering of images, video, and 3D graphics. A discrete GPU has its own VRAM." },
  { term:"HDD",     def:"Hard Disk Drive — magnetic spinning platter storage. Slower and more fragile than SSDs but cheaper per GB for bulk storage." },
  { term:"HKLM",    def:"HKEY_LOCAL_MACHINE — a root key in the Windows Registry storing hardware configuration and system-wide settings." },
  { term:"HTTPS",   def:"Hypertext Transfer Protocol Secure — HTTP encrypted with TLS. Indicated by 'https://' and a padlock icon in the browser." },
  { term:"IaaS",    def:"Infrastructure as a Service — cloud model that provides virtual hardware (VMs, storage, networking). Customer manages OS and above." },
  { term:"IMAP",    def:"Internet Message Access Protocol (port 143/993) — email protocol that keeps messages on the server, allowing access from multiple devices." },
  { term:"IoT",     def:"Internet of Things — network of physical devices (cameras, sensors, smart home devices) with embedded networking capability." },
  { term:"iGPU",    def:"Integrated Graphics Processing Unit — a GPU built into the CPU die that shares system RAM. Sufficient for everyday tasks but not gaming or 3D rendering." },
  { term:"IPSec",   def:"Internet Protocol Security — a suite of protocols for authenticating and encrypting IP packets. Used in VPNs and site-to-site tunnels." },
  { term:"KVM",     def:"Keyboard, Video, Mouse (switch) — allows one set of peripherals to control multiple computers." },
  { term:"LAN",     def:"Local Area Network — a network covering a limited geographic area such as a home, office, or building." },
  { term:"LDAP",    def:"Lightweight Directory Access Protocol (port 389/636) — used to access and maintain directory services such as Active Directory." },
  { term:"MAC",     def:"Media Access Control — a unique 48-bit hardware address assigned to every network interface card. Used for Layer 2 (local) communication." },
  { term:"MBR",     def:"Master Boot Record — the first sector of a disk containing the bootloader and partition table. Supports disks up to 2 TB with 4 primary partitions." },
  { term:"MDM",     def:"Mobile Device Management — software allowing IT to manage, monitor, enforce policies on, and remotely wipe mobile devices." },
  { term:"MFA",     def:"Multi-Factor Authentication — uses two or more verification factors (something you know, have, or are) to verify identity." },
  { term:"MIME",    def:"Multipurpose Internet Mail Extensions — a standard that extends email to support non-ASCII text, attachments, and multimedia." },
  { term:"MitM",    def:"Man-in-the-Middle — an attack where the attacker secretly intercepts and potentially alters communications between two parties." },
  { term:"NAT",     def:"Network Address Translation — maps private IP addresses to a public IP address, conserving IPv4 address space and hiding internal network structure." },
  { term:"NDA",     def:"Non-Disclosure Agreement — a legal contract requiring parties to keep specified information confidential." },
  { term:"NFC",     def:"Near Field Communication — short-range (≤4 cm) wireless technology used for contactless payments, pairing, and data transfer. Operates at 13.56 MHz." },
  { term:"NIC",     def:"Network Interface Card — hardware that connects a device to a network. Can be wired (Ethernet) or wireless (Wi-Fi)." },
  { term:"NTFS",    def:"New Technology File System — the default Windows file system supporting permissions, encryption, journaling, and large files." },
  { term:"NTP",     def:"Network Time Protocol (port 123) — synchronizes clocks across network devices. Accurate time is critical for authentication (Kerberos) and logging." },
  { term:"NVMe",    def:"Non-Volatile Memory Express — a storage protocol designed for SSDs using PCIe lanes. Far faster than SATA (up to 7 GB/s vs 600 MB/s)." },
  { term:"OFDMA",   def:"Orthogonal Frequency Division Multiple Access — Wi-Fi 6 (802.11ax) feature that divides channels into sub-channels, allowing multiple devices to transmit simultaneously." },
  { term:"OLED",    def:"Organic Light-Emitting Diode — display technology where each pixel emits its own light. Produces perfect blacks and higher contrast than LCD." },
  { term:"OS",      def:"Operating System — software that manages hardware and provides services for applications (e.g., Windows, macOS, Linux, Android, iOS)." },
  { term:"PaaS",    def:"Platform as a Service — cloud model providing a development/deployment platform. Customer manages apps and data; provider manages runtime and below." },
  { term:"PCIe",    def:"Peripheral Component Interconnect Express — high-speed expansion bus used for GPUs, NVMe SSDs, NICs, and other expansion cards." },
  { term:"PII",     def:"Personally Identifiable Information — data that can identify an individual (SSN, DOB, address, email). Protected by regulations like GDPR and HIPAA." },
  { term:"PoE",     def:"Power over Ethernet — delivers electrical power over standard Ethernet cables (IEEE 802.3af/at/bt), eliminating separate power supplies for IP cameras, VoIP phones, and APs." },
  { term:"POP3",    def:"Post Office Protocol 3 (port 110/995) — downloads email from the server to a local client. Email is typically removed from the server after download." },
  { term:"POST",    def:"Power-On Self-Test — firmware diagnostic run at startup to verify that essential hardware (CPU, RAM, storage, video) is functional before handing control to the bootloader." },
  { term:"PSU",     def:"Power Supply Unit — converts AC wall power to the DC voltages (+12V, +5V, +3.3V) required by computer components." },
  { term:"RAID",    def:"Redundant Array of Independent Disks — combines multiple drives for performance, redundancy, or both. Common levels: 0, 1, 5, 6, 10." },
  { term:"RAM",     def:"Random Access Memory — volatile, high-speed memory used to store data and instructions currently in use by the CPU. Lost when power is removed." },
  { term:"RDP",     def:"Remote Desktop Protocol (port 3389) — Microsoft protocol for remote GUI access to Windows computers." },
  { term:"RPO",     def:"Recovery Point Objective — the maximum acceptable data loss measured in time. Determines backup frequency." },
  { term:"RTO",     def:"Recovery Time Objective — the maximum acceptable time to restore a system or service after a failure." },
  { term:"SAE",     def:"Simultaneous Authentication of Equals — the handshake protocol used in WPA3 that replaces PSK, preventing offline dictionary attacks." },
  { term:"SaaS",    def:"Software as a Service — cloud-delivered software. Provider manages everything; user only manages data and access (e.g., Microsoft 365, Google Workspace)." },
  { term:"SATA",    def:"Serial ATA — interface for connecting HDDs and SSDs. SATA III max speed: ~600 MB/s. Much slower than NVMe." },
  { term:"SDS",     def:"Safety Data Sheet — document describing the hazards, handling, and disposal of chemical substances (e.g., toner cartridges, cleaning solvents)." },
  { term:"SFC",     def:"System File Checker — Windows command (sfc /scannow) that scans for and replaces corrupt system files from a cached copy." },
  { term:"SFF",     def:"Small Form Factor — compact PC chassis design commonly used in business and point-of-sale environments." },
  { term:"SMTP",    def:"Simple Mail Transfer Protocol (port 25/587) — protocol for sending email between servers and from clients to servers." },
  { term:"SNMP",    def:"Simple Network Management Protocol (port 161/162) — used to monitor and manage network devices (routers, switches, printers)." },
  { term:"SO-DIMM", def:"Small Outline DIMM — the smaller RAM form factor used in laptops and compact systems." },
  { term:"SQL",     def:"Structured Query Language — standard language for managing relational databases. SQL injection is a critical web security vulnerability." },
  { term:"SSH",     def:"Secure Shell (port 22) — encrypted protocol for remote command-line access and file transfers (SFTP/SCP). Replaces Telnet." },
  { term:"SSID",    def:"Service Set Identifier — the name of a Wi-Fi network. Broadcast by an access point; can be hidden for minimal security." },
  { term:"SSD",     def:"Solid State Drive — flash-based storage with no moving parts. Faster, more durable, and lighter than HDDs but more expensive per GB." },
  { term:"TCP",     def:"Transmission Control Protocol — connection-oriented transport protocol providing reliable, ordered, error-checked data delivery (three-way handshake)." },
  { term:"TDP",     def:"Thermal Design Power — the maximum heat a processor generates under sustained load. Used to size cooling solutions." },
  { term:"TLS",     def:"Transport Layer Security — encryption protocol for securing data in transit. TLS 1.2 and 1.3 are current standards. HTTPS uses TLS." },
  { term:"TPM",     def:"Trusted Platform Module — a hardware security chip that stores cryptographic keys. Required for Windows 11 and enables BitLocker encryption." },
  { term:"UDP",     def:"User Datagram Protocol — connectionless transport protocol. Faster than TCP but no delivery guarantee. Used by VoIP, streaming, DNS, and gaming." },
  { term:"UEFI",    def:"Unified Extensible Firmware Interface — modern replacement for BIOS. Features: GUI, mouse support, Secure Boot, GPT disk support, faster boot." },
  { term:"UPS",     def:"Uninterruptible Power Supply — provides battery backup during power outages and protects against surges and power fluctuations." },
  { term:"URL",     def:"Uniform Resource Locator — a web address specifying the protocol, domain, path, and optional parameters of a resource." },
  { term:"USB",     def:"Universal Serial Bus — standard interface for connecting peripherals. Current versions: USB 3.2 (5/10/20 Gbps), USB4 (40 Gbps)." },
  { term:"VDI",     def:"Virtual Desktop Infrastructure — delivers virtualized desktop environments from a server to thin clients or remote devices." },
  { term:"VLAN",    def:"Virtual Local Area Network — logically segments a physical network into isolated broadcast domains, improving security and performance." },
  { term:"VNC",     def:"Virtual Network Computing (port 5900) — cross-platform remote desktop protocol for graphical remote access." },
  { term:"VPN",     def:"Virtual Private Network — encrypts traffic between a device and a server, securing communications over untrusted networks." },
  { term:"WAN",     def:"Wide Area Network — a network spanning large geographic areas (cities, countries). The internet is the largest WAN." },
  { term:"WEP",     def:"Wired Equivalent Privacy — deprecated Wi-Fi encryption standard. Easily cracked in minutes. Never use." },
  { term:"WPA2",    def:"Wi-Fi Protected Access 2 — current minimum Wi-Fi encryption standard using CCMP/AES. WPA3 is the improved successor." },
  { term:"WPA3",    def:"Wi-Fi Protected Access 3 — latest Wi-Fi security standard using SAE, offering stronger protection against password attacks and forward secrecy." },
  { term:"WLAN",    def:"Wireless Local Area Network — a LAN using Wi-Fi (IEEE 802.11) instead of physical cables." },
];

GLOSSARY.sort((a, b) => a.term.localeCompare(b.term));
