const REFERENCE_SECTIONS = [
  {
    id: "ports",
    title: "Common Ports & Protocols",
    exam: "core1",
    type: "table",
    columns: ["Port(s)", "Protocol / Service", "Transport", "Notes"],
    rows: [
      ["20", "FTP (Data)", "TCP", "Active mode data transfer"],
      ["21", "FTP (Control)", "TCP", "Command channel"],
      ["22", "SSH / SFTP / SCP", "TCP", "Secure remote shell & file transfer"],
      ["23", "Telnet", "TCP", "Unencrypted remote shell — avoid"],
      ["25", "SMTP", "TCP", "Sending email between servers"],
      ["53", "DNS", "TCP/UDP", "UDP for queries; TCP for zone transfers"],
      ["67", "DHCP (Server)", "UDP", "Server listens"],
      ["68", "DHCP (Client)", "UDP", "Client listens"],
      ["69", "TFTP", "UDP", "Trivial FTP — used by PXE boot"],
      ["80", "HTTP", "TCP", "Unencrypted web traffic"],
      ["110", "POP3", "TCP", "Download email (older)"],
      ["119", "NNTP", "TCP", "Usenet newsgroups"],
      ["123", "NTP", "UDP", "Network time synchronization"],
      ["137-139", "NetBIOS", "TCP/UDP", "Windows name resolution (legacy)"],
      ["143", "IMAP", "TCP", "Email retrieval (leaves on server)"],
      ["161", "SNMP", "UDP", "Network device monitoring"],
      ["162", "SNMP Trap", "UDP", "Device-initiated alerts"],
      ["389", "LDAP", "TCP", "Directory services (Active Directory)"],
      ["443", "HTTPS", "TCP", "Encrypted web traffic (TLS)"],
      ["445", "SMB / CIFS", "TCP", "Windows file sharing"],
      ["465", "SMTPS", "TCP", "SMTP over SSL (deprecated, use 587)"],
      ["587", "SMTP Submission", "TCP", "Sending email from clients"],
      ["636", "LDAPS", "TCP", "Secure LDAP over TLS"],
      ["993", "IMAPS", "TCP", "Secure IMAP over TLS"],
      ["995", "POP3S", "TCP", "Secure POP3 over TLS"],
      ["1433", "MSSQL", "TCP", "Microsoft SQL Server"],
      ["1723", "PPTP", "TCP", "Older VPN protocol (avoid)"],
      ["3306", "MySQL", "TCP", "MySQL/MariaDB database"],
      ["3389", "RDP", "TCP", "Windows Remote Desktop Protocol"],
      ["5900", "VNC", "TCP", "Virtual Network Computing (remote desktop)"],
      ["8080", "HTTP Alt", "TCP", "Common alternate HTTP / web proxy port"],
    ]
  },
  {
    id: "wifi",
    title: "Wi-Fi Standards (802.11)",
    exam: "core1",
    type: "table",
    columns: ["Standard", "Name", "Band(s)", "Max Speed", "Key Feature"],
    rows: [
      ["802.11a", "Wi-Fi 1", "5 GHz", "54 Mbps", "First 5 GHz standard; limited range"],
      ["802.11b", "Wi-Fi 2", "2.4 GHz", "11 Mbps", "Early consumer standard"],
      ["802.11g", "Wi-Fi 3", "2.4 GHz", "54 Mbps", "Backward compatible with 802.11b"],
      ["802.11n", "Wi-Fi 4", "2.4 / 5 GHz", "600 Mbps", "Introduced MIMO & dual-band"],
      ["802.11ac", "Wi-Fi 5", "5 GHz", "3.5 Gbps", "MU-MIMO, beamforming, 160 MHz channels"],
      ["802.11ax", "Wi-Fi 6", "2.4 / 5 GHz", "9.6 Gbps", "OFDMA, Target Wake Time (TWT), BSS Coloring"],
      ["802.11ax", "Wi-Fi 6E", "2.4 / 5 / 6 GHz", "9.6 Gbps", "Adds uncongested 6 GHz band"],
      ["802.11be", "Wi-Fi 7", "2.4 / 5 / 6 GHz", "46 Gbps", "Multi-Link Operation (MLO)"],
    ]
  },
  {
    id: "usb",
    title: "USB Speed Standards",
    exam: "core1",
    type: "table",
    columns: ["Standard", "Marketing Name", "Speed", "Connector(s)"],
    rows: [
      ["USB 2.0", "Hi-Speed", "480 Mbps", "Type-A, Type-B, Micro, Mini"],
      ["USB 3.2 Gen 1", "USB 3.0 / SuperSpeed", "5 Gbps", "Type-A, Type-C"],
      ["USB 3.2 Gen 2", "SuperSpeed+", "10 Gbps", "Type-A, Type-C"],
      ["USB 3.2 Gen 2x2", "SuperSpeed 20G", "20 Gbps", "Type-C only"],
      ["USB4 Gen 2x2", "USB4 20G", "20 Gbps", "Type-C (Thunderbolt 3 compatible)"],
      ["USB4 Gen 3x2", "USB4 40G", "40 Gbps", "Type-C (Thunderbolt 4 compatible)"],
      ["Thunderbolt 3", "TB3", "40 Gbps", "Type-C — also supports DP 1.4, PCIe"],
      ["Thunderbolt 4", "TB4", "40 Gbps", "Type-C — stricter certification than TB3"],
    ]
  },
  {
    id: "cables",
    title: "Copper Cable Categories",
    exam: "core1",
    type: "table",
    columns: ["Category", "Max Speed", "Max Distance", "Common Use"],
    rows: [
      ["Cat5", "100 Mbps", "100 m", "Legacy — not recommended for new installs"],
      ["Cat5e", "1 Gbps", "100 m", "Minimum for new installs; most homes"],
      ["Cat6", "1 Gbps / 10 Gbps", "100 m / 55 m", "Office standard; 10G limited to 55m"],
      ["Cat6a", "10 Gbps", "100 m", "Augmented; supports 10G at full 100m"],
      ["Cat7", "10 Gbps", "100 m", "Shielded (STP); not officially TIA-recognized"],
      ["Cat8", "25–40 Gbps", "30 m", "Data center, short runs between switches"],
    ]
  },
  {
    id: "fiber",
    title: "Fiber Optic Cable Types",
    exam: "core1",
    type: "table",
    columns: ["Type", "Core Size", "Max Distance", "Connector Types", "Notes"],
    rows: [
      ["Single-Mode (SMF)", "8–10 µm", "Up to 100 km+", "LC, SC, ST", "One light path; used in long-haul / campus backbones"],
      ["Multi-Mode OM3", "50 µm", "300 m @ 10G", "LC, SC", "Short distances; data centers"],
      ["Multi-Mode OM4", "50 µm", "400 m @ 10G", "LC, SC", "Higher bandwidth than OM3"],
      ["Multi-Mode OM5", "50 µm", "150 m @ 100G", "LC, SC", "Wideband multimode; supports SWDM"],
    ]
  },
  {
    id: "raid",
    title: "RAID Levels",
    exam: "core1",
    type: "table",
    columns: ["Level", "Name", "Min Drives", "Redundancy?", "Performance", "Capacity", "Notes"],
    rows: [
      ["RAID 0", "Striping", "2", "No", "Read+Write ↑↑", "100%", "Fastest; zero fault tolerance — one failure = total loss"],
      ["RAID 1", "Mirroring", "2", "Yes (1 drive)", "Read ↑, Write same", "50%", "Simplest redundancy; good for OS drives"],
      ["RAID 5", "Striping + Parity", "3", "Yes (1 drive)", "Read ↑↑, Write ↑", "~67–94%", "Most common; survives 1 drive failure"],
      ["RAID 6", "Dual Parity", "4", "Yes (2 drives)", "Read ↑↑, Write slow", "~50–88%", "Survives 2 simultaneous drive failures"],
      ["RAID 10", "Stripe + Mirror", "4", "Yes (1 per mirror)", "Read ↑↑, Write ↑", "50%", "RAID 1+0; best all-around performance & redundancy"],
    ]
  },
  {
    id: "osi",
    title: "OSI Model",
    exam: "core1",
    type: "table",
    columns: ["Layer", "Name", "Protocols / Examples", "Device", "Data Unit"],
    rows: [
      ["7", "Application", "HTTP, HTTPS, FTP, DNS, SMTP, DHCP", "—", "Data"],
      ["6", "Presentation", "TLS/SSL, JPEG, MPEG, ASCII", "—", "Data"],
      ["5", "Session", "NetBIOS, RPC, SQL sessions", "—", "Data"],
      ["4", "Transport", "TCP, UDP", "Firewall", "Segment"],
      ["3", "Network", "IP, ICMP, ARP (somewhat)", "Router", "Packet"],
      ["2", "Data Link", "Ethernet, Wi-Fi (802.11), MAC, PPP", "Switch, Bridge", "Frame"],
      ["1", "Physical", "Ethernet cables, fiber, hubs, repeaters", "Hub, Repeater, NIC", "Bit"],
    ]
  },
  {
    id: "ram",
    title: "RAM Types",
    exam: "core1",
    type: "table",
    columns: ["Type", "Voltage", "Speed Range", "Form Factor", "Notes"],
    rows: [
      ["DDR4", "1.2V", "2133–3200 MT/s", "DIMM / SO-DIMM", "Current standard for most systems"],
      ["DDR5", "1.1V", "4800–8400+ MT/s", "DIMM / SO-DIMM", "Higher bandwidth, on-die ECC; not backward compatible"],
      ["ECC DDR4/5", "Same as above", "Same as above", "DIMM (usually)", "Detects and corrects single-bit errors; servers/workstations"],
      ["LPDDR5", "1.05V", "6400+ MT/s", "BGA (soldered)", "Low-power; used in laptops and smartphones"],
    ]
  },
  {
    id: "win-commands",
    title: "Essential Windows Commands",
    exam: "core2",
    type: "table",
    columns: ["Command", "What It Does", "Key Flags"],
    rows: [
      ["ipconfig", "Show IP, subnet, gateway", "/all (full details), /release, /renew, /flushdns"],
      ["ping", "Test connectivity and latency to a host", "-t (continuous), -n [count]"],
      ["tracert", "Show hop-by-hop path to destination", "-d (no DNS lookup, faster)"],
      ["nslookup", "Query DNS for hostname/IP resolution", "Set server=8.8.8.8 to test alternate DNS"],
      ["netstat", "Show active connections and listening ports", "-an (all, numeric), -b (with process name)"],
      ["arp", "Show/manage ARP cache (IP→MAC)", "-a (display table), -d (delete entry)"],
      ["net", "Manage users, shares, services", "net user, net share, net use, net start/stop"],
      ["nbtstat", "NetBIOS name resolution stats", "-n (local names), -r (resolved by broadcast)"],
      ["sfc", "System File Checker — repair system files", "/scannow"],
      ["chkdsk", "Check and repair file system", "/f (fix errors), /r (bad sectors + /f)"],
      ["DISM", "Repair Windows component store", "/Online /Cleanup-Image /RestoreHealth"],
      ["bcdedit", "Edit boot configuration data", "/enum, /set, /delete"],
      ["bootrec", "Repair boot records (from WinRE)", "/fixmbr, /fixboot, /rebuildbcd, /scanos"],
      ["gpupdate", "Refresh Group Policy settings", "/force (immediate full refresh)"],
      ["gpresult", "Show applied Group Policy results", "/r (summary), /h report.html (HTML report)"],
      ["msconfig", "System Configuration — boot & startup", "Boot, Startup, Services tabs"],
      ["regedit", "Windows Registry Editor", "Always back up before editing!"],
      ["tasklist", "List running processes (CLI)", "/svc (show services)"],
      ["taskkill", "Kill a process by name or PID", "/f (force), /im name.exe, /pid [number]"],
      ["diskpart", "Disk partitioning tool (CLI)", "list disk, select, create, format, assign"],
      ["robocopy", "Robust file copy with sync options", "/mir (mirror), /z (restartable), /log"],
      ["netsh", "Network shell — configure IP, firewall, Wi-Fi", "netsh wlan show profiles, netsh int ip reset"],
      ["pathping", "Combines ping + tracert with packet loss stats", "Useful for diagnosing intermittent packet loss"],
    ]
  },
  {
    id: "filesystems",
    title: "File Systems Comparison",
    exam: "core2",
    type: "table",
    columns: ["File System", "Max File Size", "Max Volume", "OS Support", "Use Case"],
    rows: [
      ["FAT32", "4 GB", "2 TB (32-bit)", "Windows, macOS, Linux", "USB flash drives; universal compatibility"],
      ["exFAT", "16 EiB (theoretical)", "128 PiB", "Windows, macOS, Linux", "USB/SD cards with large files; cross-platform"],
      ["NTFS", "16 EiB", "256 TiB", "Windows (native R/W); macOS (R only)", "Windows system and data drives"],
      ["APFS", "~8 EiB", "~8 EiB", "macOS / iOS (native)", "Modern Macs; optimized for SSDs; snapshots"],
      ["HFS+", "~8 EiB", "~8 EiB", "macOS (legacy)", "Older Mac drives; being replaced by APFS"],
      ["ext4", "16 TiB", "1 EiB", "Linux (native)", "Standard Linux file system"],
    ]
  },
  {
    id: "malware",
    title: "Malware Types",
    exam: "core2",
    type: "table",
    columns: ["Type", "How It Spreads", "What It Does", "Key Removal Step"],
    rows: [
      ["Virus", "Attaches to files; spreads when files are shared", "Corrupts/deletes files, replicates", "AV scan; remove infected files"],
      ["Worm", "Self-replicates across networks (no host needed)", "Consumes bandwidth, drops payloads", "Patch vulnerability; network scan"],
      ["Trojan", "Disguised as legitimate software", "Creates backdoor, steals data", "Remove the fake app; full AV scan"],
      ["Ransomware", "Email attachment, drive-by download", "Encrypts files; demands ransom", "Restore from backup; do not pay"],
      ["Spyware", "Bundled with free software", "Logs keystrokes, steals credentials", "Anti-malware; remove source app"],
      ["Adware", "Bundled software, browser extension", "Pop-up ads, browser redirects", "Uninstall source; remove extensions"],
      ["Rootkit", "Exploit or dropped by Trojan", "Hides itself in kernel; very persistent", "Offline bootable scanner; OS reinstall"],
      ["Keylogger", "Trojan, physical device, or malware", "Records keystrokes for credential theft", "AV scan; check physical ports on PC"],
      ["Botnet", "Malware infection", "Remote-controlled for DDoS, spam, mining", "Remove malware; patch vulnerabilities"],
      ["Cryptominer", "Drive-by, trojanized software", "Uses CPU/GPU for crypto mining", "AV scan; monitor CPU usage"],
    ]
  },
  {
    id: "backups",
    title: "Backup Types",
    exam: "core2",
    type: "table",
    columns: ["Type", "What It Backs Up", "Archive Bit Cleared?", "Restore Speed", "Storage Used"],
    rows: [
      ["Full", "Everything", "Yes", "Fastest (single set)", "Highest"],
      ["Incremental", "Changes since last backup (any type)", "Yes", "Slowest (full + each incremental)", "Lowest"],
      ["Differential", "All changes since last FULL backup", "No", "Medium (full + one differential)", "Medium (grows over time)"],
      ["Snapshot", "Point-in-time volume/VM state", "N/A", "Very fast (storage-level)", "Variable (deduplication)"],
      ["Mirror", "Exact copy of source; deleted files are deleted", "No", "Fast", "Same as source"],
    ]
  },
  {
    id: "troubleshooting",
    title: "CompTIA 6-Step Troubleshooting Methodology",
    exam: "core1",
    type: "list",
    items: [
      { step: "1. Identify the problem", detail: "Gather information from the user. Ask what changed recently. Reproduce the issue if possible. Check for error messages." },
      { step: "2. Establish a theory of probable cause", detail: "Based on symptoms, form a hypothesis. Start with the most common/obvious cause first ('question the obvious')." },
      { step: "3. Test the theory", detail: "Perform targeted tests to confirm or rule out your theory. If it fails, establish a new theory or escalate." },
      { step: "4. Establish an action plan", detail: "Determine the best solution considering impact, downtime, and cost. Obtain approval if needed." },
      { step: "5. Implement the solution or escalate", detail: "Apply the fix. If the solution exceeds your expertise or authorization, escalate to the appropriate level." },
      { step: "6. Verify full system functionality and document", detail: "Confirm the fix works and no new issues were introduced. Document: problem, cause, solution, and lessons learned." },
    ]
  },
  {
    id: "security-protocols",
    title: "Security Protocols & Standards",
    exam: "core2",
    type: "table",
    columns: ["Protocol / Standard", "Purpose", "Status / Notes"],
    rows: [
      ["WEP", "Wi-Fi encryption", "Deprecated — easily cracked; never use"],
      ["WPA (TKIP)", "Wi-Fi encryption", "Deprecated — vulnerable"],
      ["WPA2 (CCMP/AES)", "Wi-Fi encryption", "Current minimum — widely deployed"],
      ["WPA3 (SAE)", "Wi-Fi encryption", "Current best — resists offline attacks; use when available"],
      ["SSL 2.0 / 3.0", "Transport encryption", "Deprecated — vulnerable (POODLE attack)"],
      ["TLS 1.0 / 1.1", "Transport encryption", "Deprecated — disabled in modern browsers"],
      ["TLS 1.2", "Transport encryption", "Acceptable — widely used"],
      ["TLS 1.3", "Transport encryption", "Current best — faster handshake, perfect forward secrecy"],
      ["SSH v2", "Secure remote shell", "Standard — SSH v1 deprecated"],
      ["IPSec", "VPN / network layer encryption", "Used in site-to-site VPNs and IKEv2 VPNs"],
      ["HTTPS", "Encrypted web traffic", "HTTP over TLS/SSL — look for padlock in browser"],
      ["SFTP", "Secure file transfer", "FTP over SSH — port 22"],
      ["FTPS", "Secure file transfer", "FTP over TLS — port 990 (implicit) or 21 (explicit)"],
    ]
  },
];
